### ISSUE TITLE
Bash Script?

### ISSUE THREAD

**Issue by dgarner-cg** [anandslab/deployarr#18]
If I purchase a membership of a certain level, will I be provided with bash script to customize and add modules myself?

**Comment by anandslab** [comment]
Sorry, no. At this point, the script is not open.

**Comment by dgarner-cg** [comment]
Fair enough, I was considering the platinum membership but not if script isn’t open.

Thanks anyway!


Duane A. Garner, C.R.S.S.,
Mobile: (502) 528 - 3336
Office: (551) 307-6202
Business: ***@***.***


Infrastructure Architect, Critical Communications, United Parcel Service
http://ups.com
Chief Executive Officer, Threat Level Gaming, LLC   https://www.threatlevel.gg - https://discord.gg/tlgg
Chief Executive Officer, Catalyst Group, LLC & NextLevel Analytics, a division of Catalyst Group
https://www.catalystgroup.gg - https://cghq.me
Director of IT and Security, Eastern Shore Recovery Foundation, 501(c)3
https://esrecovery.org

This message (including any attachments) may contain confidential, proprietary, privileged and/or private information. The information is intended to be for the use of the individual or entity designated above. If you are not the intended recipient of this message, please notify the sender immediately, and delete the message and any attachments. Any disclosure, reproduction, distribution or other use of this message or any attachments by an individual or entity other than the intended recipient is prohibited.
