### ISSUE TITLE
[Request] Add SearxNG

### ISSUE THREAD

**Issue by w-gitops** [anandslab/deployarr#22]
Hi All! Would love to see a deployarr script for SearxNG!  Huge fan of self hosting and privacy issues, and this seems like a really nice thing to have.

https://github.com/searxng/searxng

Compose Example:
https://github.com/searxng/searxng-docker 

Potentially Volunteering to do the work, just not sure how to test prototype scripts..

**Comment by anandslab** [comment]
added to v5.4
