### ISSUE TITLE
Error when lauch app: /dev/fd/63: line 20: 11Wd: command not found

### ISSUE THREAD

**Issue by tiberio87** [anandslab/deployarr#5]
Hi, i have this error when lauch app

`
 ██████╗ ███████╗██████╗ ██╗      ██████╗ ██╗   ██╗ █████╗ ██████╗ ██████╗
 ██╔══██╗██╔════╝██╔══██╗██║     ██╔═══██╗╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
 ██║  ██║█████╗  ██████╔╝██║     ██║   ██║ ╚████╔╝ ███████║██████╔╝██████╔╝
 ██║  ██║██╔══╝  ██╔═══╝ ██║     ██║   ██║  ╚██╔╝  ██╔══██║██╔══██╗██╔══██╗
 ██████╔╝███████╗██║     ███████╗╚██████╔╝   ██║   ██║  ██║██║  ██║██║  ██║
 ╚═════╝ ╚══════╝╚═╝     ╚══════╝ ╚═════╝    ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝

                         by Anand - AnandsLab.com

[NOTE] Root privilege is required for this script. You will be asked for your password.

################# Version Check #############

[INFO] You are running latest version of the script: 4.6.1

The script will automatically continue in 60 seconds. Or, press any key to continue now...
/dev/fd/63: line 20: 11Wd: command not found
/dev/fd/63: line 20: 11Wd: command not found`

**Comment by anandslab** [comment]
Are you using any password with special characters? For some complex passwords have led to these errors. Usually exiting and redoing what you were doing before should help. 

Hop on to our discord so I can help you out privately.

**Comment by tiberio87** [comment]
The program works even without restarting it, I just wanted to understand the meaning of that error. Thanks
